#!/bin/bash
cd "$(dirname "$0")/presentation"
while true; do
  for f in *.md;
  do
		outputPath="${f/md/html}"
		echo '<head><meta charset="UTF-8"></head>' > "$outputPath"
    pandoc "$f" >> "$outputPath"
  done; sleep 1;
done
